### ISSUE TITLE
FTBFS with nixpkgs/0ecdcde81f922b841394c38ede5084ab162002f1

### ISSUE THREAD

**Issue by gauravjuvekar** [symphorien/nix-du#23]
```
$ nix build github:NixOS/nixpkgs/0ecdcde81f922b841394c38ede5084ab162002f1#nix-du
error: builder for '/nix/store/n9imvba0qjsm4bkmbp9cy2m3ji7war5d-nix-du-1.2.0.drv' failed with exit code 101;
       last 10 log lines:
       >
       > error[E0425]: cannot find function `populateGraph` in module `bindings`
       >    --> src/depgraph.rs:403:38
       >     |
       > 403 |         let res = unsafe { bindings::populateGraph(gptr, rootptr as *const std::os::raw::c_char) };
       >     |                                      ^^^^^^^^^^^^^ not found in `bindings`
       >
       > Some errors have detailed explanations: E0412, E0425.
       > For more information about an error, try `rustc --explain E0412`.
       > error: could not compile `nix-du` (bin "nix-du") due to 4 previous errors
       For full logs, run 'nix log /nix/store/n9imvba0qjsm4bkmbp9cy2m3ji7war5d-nix-du-1.2.0.drv'.
```

```bash
sourcing setup hook '/nix/store/65lhpq7pbc6nnngfp030ddglb71xixg9-pkg-config-wrapper-0.29.2/nix-support/setup-hook'
sourcing setup hook '/nix/store/csrcj1br0v154icbl7xw4l9d5h419692-rust-bindgen-hook/nix-support/setup-hook'
sourcing setup hook '/nix/store/h05y62lqg5cj9p8bvkd3al6h78zccnd1-cargo-build-hook.sh/nix-support/setup-hook'
sourcing setup hook '/nix/store/sijfvqmybvb0814wa3zg1w7asl3v1ns8-cargo-check-hook.sh/nix-support/setup-hook'
sourcing setup hook '/nix/store/wsax715m0q7j32dcz8wfl14628ypg43l-cargo-install-hook.sh/nix-support/setup-hook'
sourcing setup hook '/nix/store/b2n79s0vfxq86drqyk5808gfini5c4z1-cargo-setup-hook.sh/nix-support/setup-hook'
sourcing setup hook '/nix/store/dv5vgsw8naxnkcc88x78vprbnn1pp44y-patchelf-0.15.0/nix-support/setup-hook'
sourcing setup hook '/nix/store/i4iynx9axbq23sd0gyrc5wdb46zz6z8l-update-autotools-gnu-config-scripts-hook/nix-support/setup-hook'
sourcing setup hook '/nix/store/h9lc1dpi14z7is86ffhl3ld569138595-audit-tmpdir.sh'
sourcing setup hook '/nix/store/m54bmrhj6fqz8nds5zcj97w9s9bckc9v-compress-man-pages.sh'
sourcing setup hook '/nix/store/wgrbkkaldkrlrni33ccvm3b6vbxzb656-make-symlinks-relative.sh'
sourcing setup hook '/nix/store/5yzw0vhkyszf2d179m0qfkgxmp5wjjx4-move-docs.sh'
sourcing setup hook '/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh'
sourcing setup hook '/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh'
sourcing setup hook '/nix/store/pag6l61paj1dc9sv15l7bm5c17xn5kyk-move-systemd-user-units.sh'
sourcing setup hook '/nix/store/jivxp510zxakaaic7qkrb7v1dd2rdbw9-multiple-outputs.sh'
sourcing setup hook '/nix/store/ilaf1w22bxi6jsi45alhmvvdgy4ly3zs-patch-shebangs.sh'
sourcing setup hook '/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh'
sourcing setup hook '/nix/store/xyff06pkhki3qy1ls77w10s0v79c9il0-reproducible-builds.sh'
sourcing setup hook '/nix/store/aazf105snicrlvyzzbdj85sx4179rpfp-set-source-date-epoch-to-latest.sh'
sourcing setup hook '/nix/store/gps9qrh99j7g02840wv5x78ykmz30byp-strip.sh'
sourcing setup hook '/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/nix-support/setup-hook'
sourcing setup hook '/nix/store/pg90p34kys2famxnq7925sbgj4jrnsi8-binutils-wrapper-2.42/nix-support/setup-hook'
calling 'envHostTargetHook' function hook 'pkgConfigWrapper_addPkgConfigPath' /nix/store/jh97w6dp6jdpdlx830dl4d1lk6z1sgc3-boost-1.81.0-dev
calling 'envHostTargetHook' function hook 'ccWrapper_addCVars' /nix/store/jh97w6dp6jdpdlx830dl4d1lk6z1sgc3-boost-1.81.0-dev
calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/jh97w6dp6jdpdlx830dl4d1lk6z1sgc3-boost-1.81.0-dev
calling 'envHostTargetHook' function hook 'pkgConfigWrapper_addPkgConfigPath' /nix/store/qj53z29ylq7m9kwh3g63rdk30ssqxwwq-boost-1.81.0
calling 'envHostTargetHook' function hook 'ccWrapper_addCVars' /nix/store/qj53z29ylq7m9kwh3g63rdk30ssqxwwq-boost-1.81.0
calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/qj53z29ylq7m9kwh3g63rdk30ssqxwwq-boost-1.81.0
calling 'envHostTargetHook' function hook 'pkgConfigWrapper_addPkgConfigPath' /nix/store/vs8jc6c4sxa5c6sqfd68vm1cxw3cip51-nix-2.18.5-dev
calling 'envHostTargetHook' function hook 'ccWrapper_addCVars' /nix/store/vs8jc6c4sxa5c6sqfd68vm1cxw3cip51-nix-2.18.5-dev
calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/vs8jc6c4sxa5c6sqfd68vm1cxw3cip51-nix-2.18.5-dev
calling 'envHostTargetHook' function hook 'pkgConfigWrapper_addPkgConfigPath' /nix/store/bfhsxxz655clwxgsg8946v7v84f60wa4-boehm-gc-8.2.6-dev
calling 'envHostTargetHook' function hook 'ccWrapper_addCVars' /nix/store/bfhsxxz655clwxgsg8946v7v84f60wa4-boehm-gc-8.2.6-dev
calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/bfhsxxz655clwxgsg8946v7v84f60wa4-boehm-gc-8.2.6-dev
calling 'envHostTargetHook' function hook 'pkgConfigWrapper_addPkgConfigPath' /nix/store/0a98hc6zsq7bq90l2c3wyb9dz269g57n-boehm-gc-8.2.6
calling 'envHostTargetHook' function hook 'ccWrapper_addCVars' /nix/store/0a98hc6zsq7bq90l2c3wyb9dz269g57n-boehm-gc-8.2.6
calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/0a98hc6zsq7bq90l2c3wyb9dz269g57n-boehm-gc-8.2.6
calling 'envHostTargetHook' function hook 'pkgConfigWrapper_addPkgConfigPath' /nix/store/hfzbnx2hlb4yz69dfdhrldllbg1ggpqw-nlohmann_json-3.11.3
calling 'envHostTargetHook' function hook 'ccWrapper_addCVars' /nix/store/hfzbnx2hlb4yz69dfdhrldllbg1ggpqw-nlohmann_json-3.11.3
calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/hfzbnx2hlb4yz69dfdhrldllbg1ggpqw-nlohmann_json-3.11.3
calling 'envHostTargetHook' function hook 'pkgConfigWrapper_addPkgConfigPath' /nix/store/pf3c5fg5jb2mfa3ysmayk4xv2r9wb8iw-nix-2.18.5
calling 'envHostTargetHook' function hook 'ccWrapper_addCVars' /nix/store/pf3c5fg5jb2mfa3ysmayk4xv2r9wb8iw-nix-2.18.5
calling 'envHostTargetHook' function hook 'bintoolsWrapper_addLDVars' /nix/store/pf3c5fg5jb2mfa3ysmayk4xv2r9wb8iw-nix-2.18.5
evaling implicit 'postHook' string hook
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/2yppmhyn1z15kz38q7r863zdc11x3n5j-source
calling 'unpackCmd' function hook '_defaultUnpack' /nix/store/2yppmhyn1z15kz38q7r863zdc11x3n5j-source
source root is source
evaling implicit 'postUnpack' string hook
calling 'postUnpack' function hook 'cargoSetupPostUnpackHook'
Executing cargoSetupPostUnpackHook
unpacking source archive /nix/store/clccw4pi86q7qxwsasclmf57fs6skamm-nix-du-1.2.0-vendor.tar.gz
calling 'unpackCmd' function hook '_defaultUnpack' /nix/store/clccw4pi86q7qxwsasclmf57fs6skamm-nix-du-1.2.0-vendor.tar.gz
Finished cargoSetupPostUnpackHook
calling 'postUnpack' function hook '_updateSourceDateEpochFromSourceRoot'
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
calling 'postPatch' function hook 'cargoSetupPostPatchHook'
Executing cargoSetupPostPatchHook
Validating consistency between /build/source/Cargo.lock and /build/nix-du-1.2.0-vendor.tar.gz/Cargo.lock
Finished cargoSetupPostPatchHook
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
calling 'preConfigure' function hook '_multioutConfig'
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing cargoBuildHook
++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/cc HOST_CXX=/nix/store/62zpnw69ylcfhcpy1di8152zlzmbls91-gcc-wrapper-13.3.0/bin/c++ cargo build -j 32 --target x86_64-unknown-linux-gnu --offline --profile release
[1m[33mwarning[0m[1m:[0m `/build/.cargo/config` is deprecated in favor of `config.toml`
[1m[36mnote[0m[1m:[0m if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
[1m[33mwarning[0m[1m:[0m `/build/.cargo/config` is deprecated in favor of `config.toml`
[1m[36mnote[0m[1m:[0m if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
[1m[32m   Compiling[0m autocfg v1.1.0
[1m[32m   Compiling[0m libm v0.2.8
[1m[32m   Compiling[0m proc-macro2 v1.0.70
[1m[32m   Compiling[0m unicode-ident v1.0.12
[1m[32m   Compiling[0m libc v0.2.151
[1m[32m   Compiling[0m rustix v0.38.28
[1m[32m   Compiling[0m semver v1.0.20
[1m[32m   Compiling[0m memchr v2.6.4
[1m[32m   Compiling[0m scopeguard v1.2.0
[1m[32m   Compiling[0m glob v0.3.1
[1m[32m   Compiling[0m cfg-if v1.0.0
[1m[32m   Compiling[0m minimal-lexical v0.2.1
[1m[32m   Compiling[0m byteorder v1.5.0
[1m[32m   Compiling[0m prettyplease v0.2.15
[1m[32m   Compiling[0m crossbeam-utils v0.8.17
[1m[32m   Compiling[0m smallvec v1.11.2
[1m[32m   Compiling[0m either v1.9.0
[1m[32m   Compiling[0m syn v1.0.109
[1m[32m   Compiling[0m bitflags v2.4.1
[1m[32m   Compiling[0m lazy_static v1.4.0
[1m[32m   Compiling[0m paste v1.0.14
[1m[32m   Compiling[0m linux-raw-sys v0.4.12
[1m[32m   Compiling[0m stable_deref_trait v1.2.0
[1m[32m   Compiling[0m bytemuck v1.14.0
[1m[32m   Compiling[0m regex-syntax v0.8.2
[1m[32m   Compiling[0m utf8parse v0.2.1
[1m[32m   Compiling[0m bindgen v0.69.1
[1m[32m   Compiling[0m serde v1.0.193
[1m[32m   Compiling[0m home v0.5.9
[1m[32m   Compiling[0m libloading v0.7.4
[1m[32m   Compiling[0m typenum v1.17.0
[1m[32m   Compiling[0m rayon-core v1.12.0
[1m[32m   Compiling[0m anstyle-parse v0.2.3
[1m[32m   Compiling[0m colorchoice v1.0.0
[1m[32m   Compiling[0m shlex v1.2.0
[1m[32m   Compiling[0m anstyle v1.0.4
[1m[32m   Compiling[0m safe_arch v0.7.1
[1m[32m   Compiling[0m itertools v0.12.0
[1m[32m   Compiling[0m itertools v0.11.0
[1m[32m   Compiling[0m hash32 v0.2.1
[1m[32m   Compiling[0m rustc-hash v1.1.0
[1m[32m   Compiling[0m anstyle-query v1.0.2
[1m[32m   Compiling[0m rawpointer v0.2.1
[1m[32m   Compiling[0m lazycell v1.3.0
[1m[32m   Compiling[0m log v0.4.20
[1m[32m   Compiling[0m hashbrown v0.14.3
[1m[32m   Compiling[0m peeking_take_while v0.1.2
[1m[32m   Compiling[0m portable-atomic v1.6.0
[1m[32m   Compiling[0m parking_lot_core v0.9.9
[1m[32m   Compiling[0m anstream v0.6.5
[1m[32m   Compiling[0m geographiclib-rs v0.2.3
[1m[32m   Compiling[0m float_next_after v1.0.0
[1m[32m   Compiling[0m strsim v0.10.0
[1m[32m   Compiling[0m unicode-width v0.1.11
[1m[32m   Compiling[0m itoa v1.0.10
[1m[32m   Compiling[0m heck v0.4.1
[1m[32m   Compiling[0m ryu v1.0.16
[1m[32m   Compiling[0m equivalent v1.0.1
[1m[32m   Compiling[0m robust v0.2.3
[1m[32m   Compiling[0m clap_lex v0.6.0
[1m[32m   Compiling[0m rustc_version v0.4.0
[1m[32m   Compiling[0m num-traits v0.2.17
[1m[32m   Compiling[0m lock_api v0.4.11
[1m[32m   Compiling[0m num-integer v0.1.45
[1m[32m   Compiling[0m clang-sys v1.6.1
[1m[32m   Compiling[0m memoffset v0.9.0
[1m[32m   Compiling[0m num-bigint v0.4.4
[1m[32m   Compiling[0m aho-corasick v1.1.2
[1m[32m   Compiling[0m nom v7.1.3
[1m[32m   Compiling[0m num-rational v0.4.1
[1m[32m   Compiling[0m matrixmultiply v0.3.8
[1m[32m   Compiling[0m quote v1.0.33
[1m[32m   Compiling[0m spin v0.9.8
[1m[32m   Compiling[0m num-iter v0.1.43
[1m[32m   Compiling[0m syn v2.0.41
[1m[32m   Compiling[0m heapless v0.7.17
[1m[32m   Compiling[0m crossbeam-epoch v0.9.16
[1m[32m   Compiling[0m wide v0.7.13
[1m[32m   Compiling[0m csv-core v0.1.11
[1m[32m   Compiling[0m pkg-config v0.3.27
[1m[32m   Compiling[0m indexmap v2.1.0
[1m[32m   Compiling[0m number_prefix v0.4.0
[1m[32m   Compiling[0m maplit v1.0.2
[1m[32m   Compiling[0m crossbeam-deque v0.8.4
[1m[32m   Compiling[0m same-file v1.0.6
[1m[32m   Compiling[0m fixedbitset v0.4.2
[1m[32m   Compiling[0m once_cell v1.19.0
[1m[32m   Compiling[0m walkdir v2.4.0
[1m[32m   Compiling[0m approx v0.5.1
[1m[32m   Compiling[0m num-complex v0.4.4
[1m[32m   Compiling[0m rstar v0.10.0
[1m[32m   Compiling[0m cc v1.0.83
[1m[32m   Compiling[0m earcutr v0.4.3
[1m[32m   Compiling[0m float-cmp v0.9.0
[1m[32m   Compiling[0m petgraph v0.6.4
[1m[32m   Compiling[0m rayon v1.8.0
[1m[32m   Compiling[0m bytesize v1.3.0
[1m[32m   Compiling[0m regex-automata v0.4.3
[1m[32m   Compiling[0m console v0.15.7
[1m[32m   Compiling[0m geo-types v0.7.12
[1m[32m   Compiling[0m dashmap v5.5.3
[1m[32m   Compiling[0m indicatif v0.17.7
[1m[32m   Compiling[0m cexpr v0.6.0
[1m[32m   Compiling[0m versions v6.0.0
[1m[32m   Compiling[0m simba v0.8.1
[1m[32m   Compiling[0m terminal_size v0.3.0
[1m[32m   Compiling[0m clap_builder v4.4.11
[1m[32m   Compiling[0m geo v0.25.1
[1m[32m   Compiling[0m which v4.4.2
[1m[32m   Compiling[0m num v0.4.1
[1m[32m   Compiling[0m csv v1.3.0
[1m[32m   Compiling[0m regex v1.10.2
[1m[32m   Compiling[0m nalgebra-macros v0.2.1
[1m[32m   Compiling[0m enum-map-derive v0.17.0
[1m[32m   Compiling[0m clap_derive v4.4.7
[1m[32m   Compiling[0m serde_derive v1.0.193
[1m[32m   Compiling[0m enum-map v2.7.3
[1m[32m   Compiling[0m nalgebra v0.32.3
[1m[32m   Compiling[0m clap v4.4.11
[1m[32m   Compiling[0m nix-du v1.2.0 (/build/source)
[1m[32m   Compiling[0m scarlet v1.2.0
[0m[1m[38;5;9merror[E0412][0m[0m[1m: cannot find type `path_t` in module `bindings`[0m
[0m   [0m[0m[1m[38;5;12m--> [0m[0msrc/depgraph.rs:276:33[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m276[0m[0m [0m[0m[1m[38;5;12m|[0m[0m [0m[0m    unsafe fn new(p: &bindings::path_t) -> Self {[0m
[0m    [0m[0m[1m[38;5;12m| [0m[0m                                [0m[0m[1m[38;5;9m^^^^^^[0m[0m [0m[0m[1m[38;5;9mnot found in `bindings`[0m

[0m[1m[38;5;9merror[E0412][0m[0m[1m: cannot find type `path_t` in module `bindings`[0m
[0m   [0m[0m[1m[38;5;12m--> [0m[0msrc/depgraph.rs:368:78[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m368[0m[0m [0m[0m[1m[38;5;12m|[0m[0m [0m[0mpub unsafe extern "C" fn register_node(g: *mut DepGraph, p: *const bindings::path_t) {[0m
[0m    [0m[0m[1m[38;5;12m| [0m[0m                                                                             [0m[0m[1m[38;5;9m^^^^^^[0m[0m [0m[0m[1m[38;5;9mnot found in `bindings`[0m

[0m[1m[38;5;9merror[E0412][0m[0m[1m: cannot find type `path_t` in module `bindings`[0m
[0m   [0m[0m[1m[38;5;12m--> [0m[0msrc/depgraph.rs:369:23[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m369[0m[0m [0m[0m[1m[38;5;12m|[0m[0m [0m[0m    let p: &bindings::path_t = p.as_ref().unwrap();[0m
[0m    [0m[0m[1m[38;5;12m| [0m[0m                      [0m[0m[1m[38;5;9m^^^^^^[0m[0m [0m[0m[1m[38;5;9mnot found in `bindings`[0m

[0m[1m[38;5;9merror[E0425][0m[0m[1m: cannot find function `populateGraph` in module `bindings`[0m
[0m   [0m[0m[1m[38;5;12m--> [0m[0msrc/depgraph.rs:403:38[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m403[0m[0m [0m[0m[1m[38;5;12m|[0m[0m [0m[0m        let res = unsafe { bindings::populateGraph(gptr, rootptr as *const std::os::raw::c_char) };[0m
[0m    [0m[0m[1m[38;5;12m| [0m[0m                                     [0m[0m[1m[38;5;9m^^^^^^^^^^^^^[0m[0m [0m[0m[1m[38;5;9mnot found in `bindings`[0m

[0m[1mSome errors have detailed explanations: E0412, E0425.[0m
[0m[1mFor more information about an error, try `rustc --explain E0412`.[0m
[1m[31merror[0m[1m:[0m could not compile `nix-du` (bin "nix-du") due to 4 previous errors

```

**Comment by symphorien** [comment]
```
efa36d8b0dbb12461bd9ef7ca29f936ab8a7123 is the first bad commit
commit befa36d8b0dbb12461bd9ef7ca29f936ab8a7123
Author: Alyssa Ross <hi@alyssa.is>
Date:   Fri Jul 5 01:51:48 2024 +0200

    llvmPackages: 17.0.6 -> 18.1.5 on Linux (#312981)

 pkgs/top-level/all-packages.nix | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
